ci fix to test_evaluation.py::test_crps_brier_basic[crps-pd], for 'TypeError: mean() got an unexpected keyword argument 'level'' because observed was a pandas series and not a pandas dataframe